const images = {
    chatTabIcon:require('../assets/tabIcons/chat.png'),
    customersTabIcon:require('../assets/tabIcons/customers.png'),
    dashboardTabIcon:require('../assets/tabIcons/dashboard.png'),
    ticketsTabIcon:require('../assets/tabIcons/tickets.png'),
    backIcon:require('../assets/back.png'),
    chatSectionIcon:require('../assets/chat_section.png'),
    closeIcon:require('../assets/close.png'),
    customFilterIcon:require('../assets/custom_filter.png'),
    emailIcon:require('../assets/email.png'),
    facebookIcon:require('../assets/facebook.png'),
    homeIcon:require('../assets/home.png'),
    phoneOutIcon:require('../assets/phoneout.png'),
    searchIcon:require('../assets/search.png'),
    settingIcon:require('../assets/setting.png'),
    ticketPlusIcon:require('../assets/ticket_plus.png'),
    twitterIcon:require('../assets/twitter.png'),
    userIcon:require('../assets/user.png'),
    yourTicketsIcon:require('../assets/your_tickets.png'),
    logoIcon:require('../assets/logo.png'),
    sendFeedbackIcon:require('../assets/send_feedback.png'),
    clearCacheIcon:require('../assets/clear_cashe.png'),
    editItemIcon:require('../assets/edit_item.png'),
    deleteItemIcon:require('../assets/delete_item.png'),
    addCustomerIcon:require('../assets/add_customer.png'),
    chatIcon: require('../assets/chat.png'),
    arrowIcon: require('../assets/arrow.png'),
    addCompanyIcon: require('../assets/addCompany.png'),
    menuIcon: require('../assets/menu.png'),
    emptyFieldBgIcon: require('../assets/empty_field_bg.png'),
    plusIcon: require('../assets/plus.png'),
    replyItemIcon: require('../assets/reply_item.png'),
    checkIcon: require('../assets/check.png'),
    onlineStatusIcon: require('../assets/online_status.png'),
    busyStatusIcon: require('../assets/busy_status.png'),
    invisibleStatusIcon: require('../assets/invisible_status.png'),
    onlineagentIcon: require('../assets/online_agent.png'),
    offlineStatusIcon: require('../assets/offline_status.png'),

}
export default images